language: node_js
node_js:
  - 10
  - 12
  - 14
sudo: false
before_install:
  - curl -L https://unpkg.com/@pnpm/self-installer | node
install:
  - pnpm install
script:
  - npm test
notifications:
  email: false
