environment:
  matrix:
    - nodejs_version: 6
install:
  - ps: Install-Product node $env:nodejs_version
  - npm set fetch-retry-maxtimeout 180000
  - curl -L https://unpkg.com/@pnpm/self-installer | node
  - pnpm install
matrix:
  fast_finish: true
build: off
version: '{build}'
test_script:
  - node --version
  - npm --version
  - pnpm --version
  - npm test
