environment:
  matrix:
    - nodejs_version: 10
install:
  - ps: Install-Product node $env:nodejs_version
  - npm set fetch-retry-maxtimeout 180000
  - curl -f https://get.pnpm.io/v6.js | node - add --global pnpm@6
  - pnpm install
matrix:
  fast_finish: true
build: off
version: '{build}'
test_script:
  - node --version
  - npm --version
  - pnpm --version
  - pnpm test
