configDependencies:
  '@pnpm/better-defaults': 0.2.0+sha512-90iZf6xgZTlNuUVn5djvCXM720TgZrYmmb8jmjIv5c5efx3I46rmCcT2j5nlZJ6VrvghNgUaI2y/rnHe2W4L6g==
engineStrict: true
pnpmfile: node_modules/.pnpm-config/@pnpm/better-defaults/pnpmfile.cjs
