configDependencies:
  '@pnpm/better-defaults': 0.2.2+sha512-CxhLHXeW4XS/wludrcB9wgfVQmWYP0toYW5W700Aal5O6LK8qZmchvlCd/pRckBmAOWn8vT3AHokuyHvzLUv3A==

engineStrict: true

pnpmfile: node_modules/.pnpm-config/@pnpm/better-defaults/pnpmfile.cjs
